version: '3'
services:
  app:
    container_name: mypros-nextjs
    build: .
    tty: true
    volumes:
        - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev
    ports:
        - "3000:3000"
